version: '3.9'

services:
    genevill-mvc-portfolio:
        image: ${DOCKER_REGISTRY-}genevillmvcportfolio
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        container_name: portfolio
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        container_name: postgresql
        ports:
            - "8001:5432"
        environment:
            POSTGRES_PASSWORD: Your_password123
            ACCEPT_EULA: "Y"
            POSTGRES_DB: Genevill_MVC_PortfolioContext